### ISSUE TITLE
Not compatible with HTML2Minify

### ISSUE THREAD

**Issue by gravinos** [Jako/emo#10]
if the html is minified with [HTML2Minify](https://github.com/play2web/HTML2Minify) the script does not work.

**Comment by Jako** [comment]
If you get the reason for this, I will try to fix it.

**Comment by Jako** [comment]
[It's been reported that sometime inline Javascript is break, just put your Javascript code in external file.](https://github.com/play2web/HTML2Minify/blob/master/README.md#known-issues)

Since the encrypted mail addresses are created different for each resource, it is not possible to put the Javascript code in an external file. So I close this as wontfix. Maybe you could run the HTML2Minify plugin before running emo to fix the incompatibility.
